package es.unex.gc01.usersservice.model.enums;



public enum GenreType {
    HIP_HOP, RAP, TRAP, RNB, POP, ROCK, ALTERNATIVE_ROCK, HARD_ROCK,
    PUNK_ROCK, METAL, HEAVY_METAL, TRASH_METAL, INDIE, INDIE_ROCK,
    INDIE_POP, ELECTRONIC, EDM, HOUSE, TECHNO, TRANCE, DUBSTEP,
    DRUM_AND_BASS, JAZZ, BLUES, FUNK, SOUL, CLASSICAL, REGGAE,
    REGGAETON, SALSA, BACHATA, CUMBIA, FLAMENCO, FOLK, COUNTRY,
    LATIN, AFROBEAT, K_POP, J_POP, LOFI, AMBIENT, EXPERIMENTAL,
    INSTRUMENTAL, ACOUSTIC, SOUNDTRACK, GOSPEL, OPERA, DANCEHALL,
    DISCO, GRIME, DRILL, PHONK, CHILLWAVE, SYNTHWAVE, NEW_WAVE
}